DROP TYPE IF EXISTS RecipeCategory;
CREATE TYPE RecipeCategory AS ENUM (
    'Vegetarian',
    'Breakfast',
    'Dinner',
    'Snacks',
    'Sides',
    'Desserts',
    'Soups'
);

CREATE TABLE IF NOT EXISTS recipe_table (
    recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_name TEXT not NULL,
    recipe_preptime TEXT,
    recipe_ingredients TEXT NOT NULL,
    recipe_instructions TEXT NOT NULL,
    category RecipeCategory NOT NULL
);


