CREATE TABLE user_table (
    user_id INTEGER PRIMARY key generated by default AS IDENTITY,
    fullName TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

ALTER TABLE recipe_table
ADD COLUMN 
usename INTEGER REFERENCES user_table(user_id)
ON DELETE SET NULL;